export const searchData = [
  {
    job_id: "Qfh4-9t8uBZRRETpAAAAAA==",
    employer_name: "Nabu Casa",
    job_publisher: "Taro",
    job_employment_type: "FULLTIME",
    job_title: "Node.js Developer",
    job_apply_link:
      "https://www.jointaro.com/jobs/nabu-casa/nodejs-developer/?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
    job_description:
      "Nabu Casa is hiring a Node.js Developer to work on Home Assistant Cloud services, focusing on scalable and privacy-oriented features.",
    job_is_remote: false,
    job_posted_at_datetime_utc: "2024-09-04T00:04:12.000Z",
    job_city: "New York",
    job_state: "NY",
    job_country: "US",
  },
  {
    job_id: "C83Cw-r5-lY0LFYLAAAAAA==",
    employer_name: "MindPal",
    employer_logo:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTvg1jwv3mc0IzreWl9Rhg99E1WoSfFn51ynzLu&s=0",
    job_publisher: "LinkedIn",
    job_employment_type: "FULLTIME",
    job_title: "Node.JS Developer",
    job_apply_link:
      "https://www.linkedin.com/jobs/view/node-js-developer-at-mindpal-3703084347?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
    job_description:
      "We are currently seeking a talented and experienced Node.js Developer to develop and maintain server-side web applications using Node.js...",
    job_is_remote: false,
    job_posted_at_datetime_utc: "2023-08-24T16:01:03.000Z",
    job_city: "New York",
    job_state: "NY",
    job_country: "US",
  },
  {
    job_id: "J6OJSJ2un1chiLsMAAAAAA==",
    employer_name: "Dexian",
    job_publisher: "Dexian",
    job_employment_type: "FULLTIME",
    job_title: "Backend Node JS Developer (Hybrid)",
    job_apply_link:
      "https://dexian.com/jobs/backend-node-js-developer-hybrid-8035/?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
    job_description:
      "We are seeking a highly skilled Senior Backend Developer with deep expertise in JavaScript, TypeScript, and Node.js...",
    job_is_remote: false,
    job_posted_at_datetime_utc: "2024-08-26T00:00:00.000Z",
    job_city: "New York",
    job_state: "NY",
    job_country: "US",
  },
  {
    job_id: "rQod7zO11WD6rkFPAAAAAA==",
    employer_name: "MindPal",
    employer_logo:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTvg1jwv3mc0IzreWl9Rhg99E1WoSfFn51ynzLu&s=0",
    job_publisher: "LinkedIn",
    job_employment_type: "FULLTIME",
    job_title: "Fullstack Developer (Node.JS & React)",
    job_apply_link:
      "https://www.linkedin.com/jobs/view/fullstack-developer-node-js-react-at-mindpal-3706082639?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
    job_description:
      "We are seeking a skilled Node.js and React Developer to develop and maintain efficient and scalable web applications...",
    job_is_remote: false,
    job_posted_at_datetime_utc: "2023-08-28T14:30:23.000Z",
    job_city: "New York",
    job_state: "NY",
    job_country: "US",
  },
  {
    job_id: "zlkj0ZqsncKsFBHaAAAAAA==",
    employer_name: "Ampcus Inc",
    employer_logo:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQhWgTNHiu00oC0Psm6blaCAI_Sk6Jj9TIiS4c6&s=0",
    employer_website: "http://www.ampcus.com",
    job_publisher: "Talentify",
    job_employment_type: "FULLTIME",
    job_title: "Backend Developer (Node.js)",
    job_apply_link:
      "https://www.talentify.io/job/backend-developer-nodejs-fulltime-remote-us-1234567890",
    job_description:
      "Ampcus is hiring a backend developer with expertise in Node.js to build and scale cloud-native applications...",
    job_is_remote: true,
    job_posted_at_datetime_utc: "2024-08-30T00:00:00.000Z",
    job_city: "Remote",
    job_state: "N/A",
    job_country: "US",
  },
];

export const jobDetails = [
  {
    employer_name: "TEKsystems",
    employer_logo:
      "https://www.teksystems.com/-/media/teksystems/images/logos/teksystems-logo.svg?iar=0&rev=7059329eede9499a9965f7b1d91cc97f",
    employer_website: "http://www.teksystems.com",
    employer_company_type: "Staffing",
    job_publisher: "TEKsystems Careers",
    job_id: "iXki4pXSSRwAAAAAAAAAAA==",
    job_employment_type: "FULLTIME",
    job_title: "Python Developer (W2)",
    job_apply_link:
      "https://careers.teksystems.com/us/en/job/JP-003793389/Python-Developer-W2",
    job_apply_is_direct: false,
    job_apply_quality_score: 0.9674,
    job_description:
      "Description: Python Developer in Houston Texas. W2 only. Contract. Hybrid. Skills: Python, React, Linux, Unix, API Additional Skills & Qualifications: Required Skills- • Strong development experience using Python, REST API Service • 3+ years of extensive experience working as a full stack React JS developer (familiarity with redux a plus) • Database development skills, experience with Object-oriented and Relational databases - SQL Server/Oracle/Sybase. • Experience developing software using Agile methodology. • Knowledge of JIRA tools and Continuous Integration capabilities. • Familiarity with web services, web sockets and microservice based architecture is a plus • Hands on experience in writing unit and UI integration test cases. Experience Level: Intermediate Level About TEKsystems: We're partners in transformation. We help clients activate ideas and solutions to take advantage of a new world of opportunity. We are a team of 80,000 strong, working with over 6,000 clients, including 80% of the Fortune 500, across North America, Europe and Asia. As an industry leader in Full-Stack Technology Services, Talent Services, and real-world application, we work with progressive leaders to drive change. That's the power of true partnership. TEKsystems is an Allegis Group company. The company is an equal opportunity employer and will consider all applications without regards to race, sex, age, color, religion, national origin, veteran status, disability, sexual orientation, gender identity, genetic information or any characteristic protected by law.",
    job_is_remote: false,
    job_posted_at_timestamp: 1684773292,
    job_posted_at_datetime_utc: "2023-05-22T16:34:52.000Z",
    job_city: "Houston",
    job_state: "TX",
    job_country: "US",
    job_latitude: 29.760427,
    job_longitude: -95.369804,
    job_benefits: null,
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&q=iXki4pXSSRwAAAAAAAAAAA%3D%3D&cs=1&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=iXki4pXSSRwAAAAAAAAAAA%3D%3D&htidocid=iXki4pXSSRwAAAAAAAAAAA%3D%3D",
    job_offer_expiration_datetime_utc: null,
    job_offer_expiration_timestamp: null,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: 36,
      experience_mentioned: true,
      experience_preferred: true,
    },
    job_required_skills: [
      "Python",
      "Redux",
      "ui integration",
      "REST API",
      "UI",
      "Jira",
      "Full Stack",
      "Linux",
      "SQL Server",
      "Agile Methodology",
      "Unix",
      "React",
      "Oracle",
      "Continuous Integration",
      "jira tools",
      "Integration",
      "Database Development",
      "Sybase",
      "Architecture",
      "Web Services",
      "Technology Services",
      "Transformation",
      "Writing",
      "Development",
      "Senior Developer & Software Engineer .Net & Full Stack Developer & Full Stack Software Engineer .Net",
      ".Net Developer & Full Stack Developer & Full Stack Application Developer & .Net Software Engineer",
      "Big Data Developer & Java Developer",
      "Senior Software Developer - Java",
      "Swiggy Full Stack Developer - SDE I",
      "Java Developer & Software Engineer",
      "Python Developer",
      "Big Data Developer & Full Stack Developer",
      "Senior Software Engineer - Java",
      "Python",
      "Sql Relational Database",
      "Senior Software Developer - Java & J2ee & UI Developer",
    ],
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: false,
      degree_mentioned: false,
      degree_preferred: false,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_currency: null,
    job_salary_period: null,
    job_highlights: {
      Qualifications: [
        "Python, React, Linux, Unix, API",
        "Strong development experience using Python, REST API Service",
        "Database development skills, experience with Object-oriented and Relational databases - SQL Server/Oracle/Sybase",
        "Experience developing software using Agile methodology",
        "Knowledge of JIRA tools and Continuous Integration capabilities",
        "Hands on experience in writing unit and UI integration test cases",
      ],
      Responsibilities: [
        "Design, develop, and maintain efficient, reusable, and reliable Python code",
        "Collaborate with cross-functional teams to define, design, and ship new features",
        "Write clean, scalable, and well-documented code while adhering to best practices",
        "Implement unit and integration tests to ensure software quality and reliability",
        "Work closely with DevOps teams to ensure continuous integration and deployment processes",
        "Optimize application performance and troubleshoot complex software issues",
        "Participate in code reviews and provide constructive feedback to peers",
        "Ensure compliance with security and data protection standards",
        "Contribute to architectural decisions and provide technical guidance to junior developers",
        "Stay up-to-date with the latest industry trends and technologies",
      ],
      job_job_title: null,
      job_posting_language: "en",
      job_onet_soc: "15113200",
      job_onet_job_zone: "4",
    },
    job_job_title: null,
    job_posting_language: "en",
    job_onet_soc: "15113200",
    job_onet_job_zone: "4",
    job_occupational_categories: ["Developer"],
    job_naics_code: "561311",
    job_naics_name: "Employment Placement Agencies",
    estimated_salaries: null,
    apply_options: null,
    employer_reviews: [
      {
        publisher: "Glassdoor",
        employer_name: "TEKsystems",
        score: 4,
        num_stars: 4,
        review_count: 10056,
        max_score: 5,
        reviews_link:
          "https://www.glassdoor.com/Reviews/TEKsystems-Reviews-E23297.htm?utm_campaign=google_jobs_reviews&utm_source=google_jobs_reviews&utm_medium=organic",
      },
      {
        publisher: "Indeed",
        employer_name: "TEKsystems",
        score: 3.8,
        num_stars: 4,
        review_count: 4118,
        max_score: 5,
        reviews_link:
          "https://www.indeed.com/cmp/TEKsystems/reviews?utm_campaign=google_jobs_reviews&utm_source=google_jobs_reviews&utm_medium=organic",
      },
      {
        publisher: "CareerBliss",
        employer_name: "TEKsystems",
        score: 3.9,
        num_stars: 4,
        review_count: 405,
        max_score: 5,
        reviews_link:
          "https://www.careerbliss.com/teksystems/reviews/?utm_campaign=google_jobs_reviews&utm_source=google_jobs_reviews&utm_medium=organic",
      },
    ],
  },
];
